# Generated by Django 5.0.6 on 2024-05-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('cooking_instructions', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Easy'), ('INTERMEDIATE', 'Medium'), ('EXPERT', 'Hard')], max_length=50)),
            ],
        ),
    ]
