# Generated by Django 5.0.6 on 2024-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
    ]
